[workspace]
members = ["crates/ft_vr", "crates/vr_renderer"]
resolver = "2"

[workspace.dependencies]
log = "0.4.21"
ggez = { git = "https://github.com/Bloeckchengrafik/ggez.git", branch = "master" }

[profile.dev]
opt-level = 1
