[package]
name = "ft_vr"
version = "0.1.0"
edition = "2021"

[dependencies]
vr_renderer = { path = "../vr_renderer" }
input_devices = { path = "../input_devices" }
log.workspace = true
pretty_env_logger = "0.5.0"