[package]
name = "websocket_server"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
pub-sub.workspace = true
serde.workspace = true

messages = { path = "../messages" }

serde_json = "1.0"
tungstenite = "0.21.0"