[package]
name = "game_core"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
messages = { path = "../messages" }
pub-sub.workspace = true
async-trait = "0.1.83"
anyhow = "1.0.89"
tokio = { version = "1.40.0", features = ["full"] }