[package]
name = "input_devices"
version = "0.1.0"
edition = "2021"

[features]
accelerometer = []

[dependencies]
log.workspace = true
messages = { path = "../messages" }
pub-sub.workspace = true
serialport = "4.3.0"